config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/create'

  get 'bookmarks/destroy'

  get 'sessions/new'

  root'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only:[:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Penguin App Home", root_path%>
        <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <% if logged_in? %>
            <li><%= link_to "Users", '#' %></li>
                <li>
                    <%= link_to "My Account", current_user %>
                </li>
                <li>
                    <%= link_to "Edit", edit_user_path(current_user) %>
                </li>
                <li>
                    <%= button_to "Log out", logout_path, method: :delete %>
                </li>
            </li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>
        </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PenguinApp</title>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= debug(params)if Rails.env.development?%>
  </body>
</html>